//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EarthquakeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EarthquakeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.EarthquakeResources", typeof(EarthquakeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre Depth.
        /// </summary>
        public static string DetailsDepthText {
            get {
                return ResourceManager.GetString("DetailsDepthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre.
        /// </summary>
        public static string DetailsHypocentreText {
            get {
                return ResourceManager.GetString("DetailsHypocentreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DetailsIntensityText {
            get {
                return ResourceManager.GetString("DetailsIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string DetailsLastUpdatedText {
            get {
                return ResourceManager.GetString("DetailsLastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude.
        /// </summary>
        public static string DetailsMagnitudeText {
            get {
                return ResourceManager.GetString("DetailsMagnitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Intensity.
        /// </summary>
        public static string DetailsMaxIntensityText {
            get {
                return ResourceManager.GetString("DetailsMaxIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DetailsTimeText {
            get {
                return ResourceManager.GetString("DetailsTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800+ km.
        /// </summary>
        public static string EarthquakeDepthDeep {
            get {
                return ResourceManager.GetString("EarthquakeDepthDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shallow.
        /// </summary>
        public static string EarthquakeDepthShallow {
            get {
                return ResourceManager.GetString("EarthquakeDepthShallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C8C8CB.
        /// </summary>
        public static string EarthquakeIntensityUnknownColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityUnknownColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string EarthquakeIntensityUnknownText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F0F0F0.
        /// </summary>
        public static string EarthquakeIntensityZeroColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityZeroColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string EarthquakeIntensityZeroText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityZeroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8+.
        /// </summary>
        public static string EarthquakeMagnitudeHuge {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string EarthquakeMagnitudeUnitDefault {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mj.
        /// </summary>
        public static string EarthquakeMagnitudeUnitJma {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitJma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mw.
        /// </summary>
        public static string EarthquakeMagnitudeUnitMoment {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF9900.
        /// </summary>
        public static string IntensityFiveStrongColour {
            get {
                return ResourceManager.GetString("IntensityFiveStrongColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+.
        /// </summary>
        public static string IntensityFiveStrongText {
            get {
                return ResourceManager.GetString("IntensityFiveStrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFE600.
        /// </summary>
        public static string IntensityFiveWeakColour {
            get {
                return ResourceManager.GetString("IntensityFiveWeakColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-.
        /// </summary>
        public static string IntensityFiveWeakText {
            get {
                return ResourceManager.GetString("IntensityFiveWeakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FAE696.
        /// </summary>
        public static string IntensityFourColour {
            get {
                return ResourceManager.GetString("IntensityFourColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string IntensityFourText {
            get {
                return ResourceManager.GetString("IntensityFourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F2F2FF.
        /// </summary>
        public static string IntensityOneColour {
            get {
                return ResourceManager.GetString("IntensityOneColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string IntensityOneText {
            get {
                return ResourceManager.GetString("IntensityOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #B40068.
        /// </summary>
        public static string IntensitySevenColour {
            get {
                return ResourceManager.GetString("IntensitySevenColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string IntensitySevenText {
            get {
                return ResourceManager.GetString("IntensitySevenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A50021.
        /// </summary>
        public static string IntensitySixStrongColour {
            get {
                return ResourceManager.GetString("IntensitySixStrongColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6+.
        /// </summary>
        public static string IntensitySixStrongText {
            get {
                return ResourceManager.GetString("IntensitySixStrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF2800.
        /// </summary>
        public static string IntensitySixWeakColour {
            get {
                return ResourceManager.GetString("IntensitySixWeakColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-.
        /// </summary>
        public static string IntensitySixWeakText {
            get {
                return ResourceManager.GetString("IntensitySixWeakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0041FF.
        /// </summary>
        public static string IntensityThreeColour {
            get {
                return ResourceManager.GetString("IntensityThreeColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string IntensityThreeText {
            get {
                return ResourceManager.GetString("IntensityThreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00AAFF.
        /// </summary>
        public static string IntensityTwoColour {
            get {
                return ResourceManager.GetString("IntensityTwoColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string IntensityTwoText {
            get {
                return ResourceManager.GetString("IntensityTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
    }
}
