//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EarthquakeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EarthquakeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.EarthquakeResources", typeof(EarthquakeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800+ km.
        /// </summary>
        public static string DepthDeep {
            get {
                return ResourceManager.GetString("DepthDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shallow.
        /// </summary>
        public static string DepthShallow {
            get {
                return ResourceManager.GetString("DepthShallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre Depth.
        /// </summary>
        public static string DetailsDepthText {
            get {
                return ResourceManager.GetString("DetailsDepthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre.
        /// </summary>
        public static string DetailsHypocentreText {
            get {
                return ResourceManager.GetString("DetailsHypocentreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DetailsIntensityText {
            get {
                return ResourceManager.GetString("DetailsIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string DetailsLastUpdatedText {
            get {
                return ResourceManager.GetString("DetailsLastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude.
        /// </summary>
        public static string DetailsMagnitudeText {
            get {
                return ResourceManager.GetString("DetailsMagnitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Intensity.
        /// </summary>
        public static string DetailsMaxIntensityText {
            get {
                return ResourceManager.GetString("DetailsMaxIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DetailsTimeText {
            get {
                return ResourceManager.GetString("DetailsTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF9900.
        /// </summary>
        public static string IntensityColourFiveStrong {
            get {
                return ResourceManager.GetString("IntensityColourFiveStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFE600.
        /// </summary>
        public static string IntensityColourFiveWeak {
            get {
                return ResourceManager.GetString("IntensityColourFiveWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FAE696.
        /// </summary>
        public static string IntensityColourFour {
            get {
                return ResourceManager.GetString("IntensityColourFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F2F2FF.
        /// </summary>
        public static string IntensityColourOne {
            get {
                return ResourceManager.GetString("IntensityColourOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #B40068.
        /// </summary>
        public static string IntensityColourSeven {
            get {
                return ResourceManager.GetString("IntensityColourSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A50021.
        /// </summary>
        public static string IntensityColourSixStrong {
            get {
                return ResourceManager.GetString("IntensityColourSixStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF2800.
        /// </summary>
        public static string IntensityColourSixWeak {
            get {
                return ResourceManager.GetString("IntensityColourSixWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0041FF.
        /// </summary>
        public static string IntensityColourThree {
            get {
                return ResourceManager.GetString("IntensityColourThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00AAFF.
        /// </summary>
        public static string IntensityColourTwo {
            get {
                return ResourceManager.GetString("IntensityColourTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C8C8CB.
        /// </summary>
        public static string IntensityColourUnknown {
            get {
                return ResourceManager.GetString("IntensityColourUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F0F0F0.
        /// </summary>
        public static string IntensityColourZero {
            get {
                return ResourceManager.GetString("IntensityColourZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+.
        /// </summary>
        public static string IntensityTextFiveStrong {
            get {
                return ResourceManager.GetString("IntensityTextFiveStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-.
        /// </summary>
        public static string IntensityTextFiveWeak {
            get {
                return ResourceManager.GetString("IntensityTextFiveWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string IntensityTextFour {
            get {
                return ResourceManager.GetString("IntensityTextFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string IntensityTextOne {
            get {
                return ResourceManager.GetString("IntensityTextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string IntensityTextSeven {
            get {
                return ResourceManager.GetString("IntensityTextSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6+.
        /// </summary>
        public static string IntensityTextSixStrong {
            get {
                return ResourceManager.GetString("IntensityTextSixStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-.
        /// </summary>
        public static string IntensityTextSixWeak {
            get {
                return ResourceManager.GetString("IntensityTextSixWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string IntensityTextThree {
            get {
                return ResourceManager.GetString("IntensityTextThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string IntensityTextTwo {
            get {
                return ResourceManager.GetString("IntensityTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string IntensityTextUnknown {
            get {
                return ResourceManager.GetString("IntensityTextUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string IntensityTextZero {
            get {
                return ResourceManager.GetString("IntensityTextZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8+.
        /// </summary>
        public static string MagnitudeHuge {
            get {
                return ResourceManager.GetString("MagnitudeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MagnitudeUnitDefault {
            get {
                return ResourceManager.GetString("MagnitudeUnitDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mj.
        /// </summary>
        public static string MagnitudeUnitJma {
            get {
                return ResourceManager.GetString("MagnitudeUnitJma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mw.
        /// </summary>
        public static string MagnitudeUnitMoment {
            get {
                return ResourceManager.GetString("MagnitudeUnitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
    }
}
