//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PastPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PastPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.PastPageResources", typeof(PastPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre Depth.
        /// </summary>
        public static string DepthText {
            get {
                return ResourceManager.GetString("DepthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypocentre.
        /// </summary>
        public static string HypocentreText {
            get {
                return ResourceManager.GetString("HypocentreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdatedText {
            get {
                return ResourceManager.GetString("LastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load 10 More Earthquakes.
        /// </summary>
        public static string LoadMoreText {
            get {
                return ResourceManager.GetString("LoadMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude.
        /// </summary>
        public static string MagnitudeText {
            get {
                return ResourceManager.GetString("MagnitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Intensity.
        /// </summary>
        public static string MaxIntensityText {
            get {
                return ResourceManager.GetString("MaxIntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Refresh Earthquake List.
        /// </summary>
        public static string RefreshListText {
            get {
                return ResourceManager.GetString("RefreshListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo Earthquake Details.
        /// </summary>
        public static string YahooText {
            get {
                return ResourceManager.GetString("YahooText", resourceCulture);
            }
        }
    }
}
