//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured Intensity.
        /// </summary>
        public static string KmoniDataIntensity {
            get {
                return ResourceManager.GetString("KmoniDataIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Acceleration (PGA).
        /// </summary>
        public static string KmoniDataPga {
            get {
                return ResourceManager.GetString("KmoniDataPga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Displacement (PGD).
        /// </summary>
        public static string KmoniDataPgd {
            get {
                return ResourceManager.GetString("KmoniDataPgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Velocity (PGV).
        /// </summary>
        public static string KmoniDataPgv {
            get {
                return ResourceManager.GetString("KmoniDataPgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.125 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0125 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.250 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0250 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.500 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0500 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp1000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp2000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp4000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole.
        /// </summary>
        public static string KmoniSensorsBoreholeText {
            get {
                return ResourceManager.GetString("KmoniSensorsBoreholeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string KmoniSensorsSurfaceText {
            get {
                return ResourceManager.GetString("KmoniSensorsSurfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed!.
        /// </summary>
        public static string SettingsApiConfirmedText {
            get {
                return ResourceManager.GetString("SettingsApiConfirmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string SettingsApiConfirmText {
            get {
                return ResourceManager.GetString("SettingsApiConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string SettingsApiText {
            get {
                return ResourceManager.GetString("SettingsApiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key In Use.
        /// </summary>
        public static string SettingsAuthStatusApiKeyText {
            get {
                return ResourceManager.GetString("SettingsAuthStatusApiKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Configure Authentication Method.
        /// </summary>
        public static string SettingsAuthStatusNoneText {
            get {
                return ResourceManager.GetString("SettingsAuthStatusNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth 2.0 In Use.
        /// </summary>
        public static string SettingsAuthStatusOAuthText {
            get {
                return ResourceManager.GetString("SettingsAuthStatusOAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM-D.S.S. Data Service.
        /// </summary>
        public static string SettingsDmdssText {
            get {
                return ResourceManager.GetString("SettingsDmdssText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeaderText {
            get {
                return ResourceManager.GetString("SettingsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string SettingsKmoniDataText {
            get {
                return ResourceManager.GetString("SettingsKmoniDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Points:.
        /// </summary>
        public static string SettingsKmoniStationText {
            get {
                return ResourceManager.GetString("SettingsKmoniStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Monitor.
        /// </summary>
        public static string SettingsKmoniText {
            get {
                return ResourceManager.GetString("SettingsKmoniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language/言語/语言.
        /// </summary>
        public static string SettingsLangText {
            get {
                return ResourceManager.GetString("SettingsLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from OAuth 2.0.
        /// </summary>
        public static string SettingsOAuthConnectedButtonText {
            get {
                return ResourceManager.GetString("SettingsOAuthConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        public static string SettingsOAuthConnectedText {
            get {
                return ResourceManager.GetString("SettingsOAuthConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to OAuth 2.0.
        /// </summary>
        public static string SettingsOAuthDisconnectedButtonText {
            get {
                return ResourceManager.GetString("SettingsOAuthDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string SettingsStatusText {
            get {
                return ResourceManager.GetString("SettingsStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string SettingsWebSocketApplicationNameText {
            get {
                return ResourceManager.GetString("SettingsWebSocketApplicationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from WebSocket.
        /// </summary>
        public static string SettingsWebSocketConnectedButtonText {
            get {
                return ResourceManager.GetString("SettingsWebSocketConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection ID.
        /// </summary>
        public static string SettingsWebSocketConnectionIdText {
            get {
                return ResourceManager.GetString("SettingsWebSocketConnectionIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Time.
        /// </summary>
        public static string SettingsWebSocketConnectionTimeText {
            get {
                return ResourceManager.GetString("SettingsWebSocketConnectionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to WebSocket.
        /// </summary>
        public static string SettingsWebSocketDisconnectedButtonText {
            get {
                return ResourceManager.GetString("SettingsWebSocketDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string SettingsWebSocketDisconnectText {
            get {
                return ResourceManager.GetString("SettingsWebSocketDisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty Connection).
        /// </summary>
        public static string SettingsWebSocketEmptyConnectionName {
            get {
                return ResourceManager.GetString("SettingsWebSocketEmptyConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Refresh WebSocket List.
        /// </summary>
        public static string SettingsWebSocketListRefreshText {
            get {
                return ResourceManager.GetString("SettingsWebSocketListRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket Connections.
        /// </summary>
        public static string SettingsWebSocketText {
            get {
                return ResourceManager.GetString("SettingsWebSocketText", resourceCulture);
            }
        }
    }
}
