//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800+ km.
        /// </summary>
        public static string EarthquakeDepthDeep {
            get {
                return ResourceManager.GetString("EarthquakeDepthDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shallow.
        /// </summary>
        public static string EarthquakeDepthShallow {
            get {
                return ResourceManager.GetString("EarthquakeDepthShallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF9900.
        /// </summary>
        public static string EarthquakeIntensityFiveStrongColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFiveStrongColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+.
        /// </summary>
        public static string EarthquakeIntensityFiveStrongText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFiveStrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFE600.
        /// </summary>
        public static string EarthquakeIntensityFiveWeakColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFiveWeakColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-.
        /// </summary>
        public static string EarthquakeIntensityFiveWeakText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFiveWeakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FAE696.
        /// </summary>
        public static string EarthquakeIntensityFourColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFourColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string EarthquakeIntensityFourText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityFourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F2F2FF.
        /// </summary>
        public static string EarthquakeIntensityOneColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityOneColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string EarthquakeIntensityOneText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #B40068.
        /// </summary>
        public static string EarthquakeIntensitySevenColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySevenColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string EarthquakeIntensitySevenText {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySevenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A50021.
        /// </summary>
        public static string EarthquakeIntensitySixStrongColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySixStrongColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6+.
        /// </summary>
        public static string EarthquakeIntensitySixStrongText {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySixStrongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF2800.
        /// </summary>
        public static string EarthquakeIntensitySixWeakColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySixWeakColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-.
        /// </summary>
        public static string EarthquakeIntensitySixWeakText {
            get {
                return ResourceManager.GetString("EarthquakeIntensitySixWeakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0041FF.
        /// </summary>
        public static string EarthquakeIntensityThreeColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityThreeColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string EarthquakeIntensityThreeText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityThreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00AAFF.
        /// </summary>
        public static string EarthquakeIntensityTwoColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityTwoColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string EarthquakeIntensityTwoText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #C8C8CB.
        /// </summary>
        public static string EarthquakeIntensityUnknownColour {
            get {
                return ResourceManager.GetString("EarthquakeIntensityUnknownColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string EarthquakeIntensityUnknownText {
            get {
                return ResourceManager.GetString("EarthquakeIntensityUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8+.
        /// </summary>
        public static string EarthquakeMagnitudeHuge {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string EarthquakeMagnitudeUnitDefault {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mj.
        /// </summary>
        public static string EarthquakeMagnitudeUnitJma {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitJma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mw.
        /// </summary>
        public static string EarthquakeMagnitudeUnitMoment {
            get {
                return ResourceManager.GetString("EarthquakeMagnitudeUnitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured Intensity.
        /// </summary>
        public static string KmoniDataIntensity {
            get {
                return ResourceManager.GetString("KmoniDataIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Acceleration (PGA).
        /// </summary>
        public static string KmoniDataPga {
            get {
                return ResourceManager.GetString("KmoniDataPga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Displacement (PGD).
        /// </summary>
        public static string KmoniDataPgd {
            get {
                return ResourceManager.GetString("KmoniDataPgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Velocity (PGV).
        /// </summary>
        public static string KmoniDataPgv {
            get {
                return ResourceManager.GetString("KmoniDataPgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.125 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0125 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.250 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0250 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.500 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp0500 {
            get {
                return ResourceManager.GetString("KmoniDataRsp0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp1000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp2000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniDataRsp4000 {
            get {
                return ResourceManager.GetString("KmoniDataRsp4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole.
        /// </summary>
        public static string KmoniSensorsBoreholeText {
            get {
                return ResourceManager.GetString("KmoniSensorsBoreholeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string KmoniSensorsSurfaceText {
            get {
                return ResourceManager.GetString("KmoniSensorsSurfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
    }
}
