//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.SettingPageResources", typeof(SettingPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed!.
        /// </summary>
        public static string ApiConfirmedText {
            get {
                return ResourceManager.GetString("ApiConfirmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ApiConfirmText {
            get {
                return ResourceManager.GetString("ApiConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string ApiText {
            get {
                return ResourceManager.GetString("ApiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key In Use.
        /// </summary>
        public static string AuthStatusApiKeyText {
            get {
                return ResourceManager.GetString("AuthStatusApiKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Configure Authentication Method.
        /// </summary>
        public static string AuthStatusNoneText {
            get {
                return ResourceManager.GetString("AuthStatusNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth 2.0 In Use.
        /// </summary>
        public static string AuthStatusOAuthText {
            get {
                return ResourceManager.GetString("AuthStatusOAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string AuthStatusText {
            get {
                return ResourceManager.GetString("AuthStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM-D.S.S. Data Service.
        /// </summary>
        public static string DmdssText {
            get {
                return ResourceManager.GetString("DmdssText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since information is created within seconds after an earthquake, false reports may occure..
        /// </summary>
        public static string GeneralText1 {
            get {
                return ResourceManager.GetString("GeneralText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information immediately after the detection of an earthquake may have low accuracy in predicting the epicentre, the magnitude and the expected intensity..
        /// </summary>
        public static string GeneralText2 {
            get {
                return ResourceManager.GetString("GeneralText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even under normal conditions, there may be an error of one level for the estimated intensity..
        /// </summary>
        public static string GeneralText3 {
            get {
                return ResourceManager.GetString("GeneralText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for the epicentre (magnitude, depth, position) do not have seismological meaning for information only using the PLUM method or from detecting 100gal..
        /// </summary>
        public static string GeneralText4 {
            get {
                return ResourceManager.GetString("GeneralText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum expected intensity will not be reported for earthquakes with depth greater than 150km (it may be reported via PLUM method)..
        /// </summary>
        public static string GeneralText5 {
            get {
                return ResourceManager.GetString("GeneralText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the communications environment, there might be a delay of one second or more for the receival of the information after the announcement. Please use a stable connection environment with a bandwidth of at least 5Mbps..
        /// </summary>
        public static string GeneralText6 {
            get {
                return ResourceManager.GetString("GeneralText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string GeneralTextBullet {
            get {
                return ResourceManager.GetString("GeneralTextBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on EEW (Please Read).
        /// </summary>
        public static string GeneralTextHeader {
            get {
                return ResourceManager.GetString("GeneralTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string KmoniMeasurementText {
            get {
                return ResourceManager.GetString("KmoniMeasurementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured Intensity.
        /// </summary>
        public static string KmoniMeasurementTextMeasuredIntensity {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextMeasuredIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Acceleration (PGA).
        /// </summary>
        public static string KmoniMeasurementTextPeakGroundAcceleration {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextPeakGroundAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Displacement (PGD).
        /// </summary>
        public static string KmoniMeasurementTextPeakGroundDisplacement {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextPeakGroundDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Ground Velocity (PGV).
        /// </summary>
        public static string KmoniMeasurementTextPeakGroundVelocity {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextPeakGroundVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.125 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse0125 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.250 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse0250 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse0250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.500 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse0500 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse1000 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse2000 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.000 Hz PGV Response Spectrum.
        /// </summary>
        public static string KmoniMeasurementTextResponse4000 {
            get {
                return ResourceManager.GetString("KmoniMeasurementTextResponse4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Points:.
        /// </summary>
        public static string KmoniSensorText {
            get {
                return ResourceManager.GetString("KmoniSensorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole.
        /// </summary>
        public static string KmoniSensorTextBorehole {
            get {
                return ResourceManager.GetString("KmoniSensorTextBorehole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string KmoniSensorTextSurface {
            get {
                return ResourceManager.GetString("KmoniSensorTextSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Monitor.
        /// </summary>
        public static string KmoniText {
            get {
                return ResourceManager.GetString("KmoniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language / 言語 / 语言.
        /// </summary>
        public static string LangText {
            get {
                return ResourceManager.GetString("LangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from OAuth 2.0.
        /// </summary>
        public static string OAuthConnectedButtonText {
            get {
                return ResourceManager.GetString("OAuthConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        public static string OAuthConnectedText {
            get {
                return ResourceManager.GetString("OAuthConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to OAuth 2.0.
        /// </summary>
        public static string OAuthDisconnectedButtonText {
            get {
                return ResourceManager.GetString("OAuthDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string WebSocketApplicationNameText {
            get {
                return ResourceManager.GetString("WebSocketApplicationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from WebSocket.
        /// </summary>
        public static string WebSocketConnectedButtonText {
            get {
                return ResourceManager.GetString("WebSocketConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Time.
        /// </summary>
        public static string WebSocketConnectionTimeText {
            get {
                return ResourceManager.GetString("WebSocketConnectionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to WebSocket.
        /// </summary>
        public static string WebSocketDisconnectedButtonText {
            get {
                return ResourceManager.GetString("WebSocketDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string WebSocketDisconnectText {
            get {
                return ResourceManager.GetString("WebSocketDisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty Connection).
        /// </summary>
        public static string WebSocketEmptyConnectionName {
            get {
                return ResourceManager.GetString("WebSocketEmptyConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Refresh WebSocket List.
        /// </summary>
        public static string WebSocketListRefreshText {
            get {
                return ResourceManager.GetString("WebSocketListRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket Connections.
        /// </summary>
        public static string WebSocketText {
            get {
                return ResourceManager.GetString("WebSocketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection ID.
        /// </summary>
        public static string WebSocketWebSocketIdText {
            get {
                return ResourceManager.GetString("WebSocketWebSocketIdText", resourceCulture);
            }
        }
    }
}
