//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasonEetwViewer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasonEetwViewer.Lang.SettingPageResources", typeof(SettingPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed!.
        /// </summary>
        public static string ApiConfirmedText {
            get {
                return ResourceManager.GetString("ApiConfirmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ApiConfirmText {
            get {
                return ResourceManager.GetString("ApiConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string ApiText {
            get {
                return ResourceManager.GetString("ApiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key In Use.
        /// </summary>
        public static string AuthStatusApiKeyText {
            get {
                return ResourceManager.GetString("AuthStatusApiKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Configure Authentication Method.
        /// </summary>
        public static string AuthStatusNoneText {
            get {
                return ResourceManager.GetString("AuthStatusNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth 2.0 In Use.
        /// </summary>
        public static string AuthStatusOAuthText {
            get {
                return ResourceManager.GetString("AuthStatusOAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string AuthStatusText {
            get {
                return ResourceManager.GetString("AuthStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM-D.S.S. Data Service.
        /// </summary>
        public static string DmdssText {
            get {
                return ResourceManager.GetString("DmdssText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string KmoniDataText {
            get {
                return ResourceManager.GetString("KmoniDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Points:.
        /// </summary>
        public static string KmoniStationText {
            get {
                return ResourceManager.GetString("KmoniStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Monitor.
        /// </summary>
        public static string KmoniText {
            get {
                return ResourceManager.GetString("KmoniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language / 言語 / 语言.
        /// </summary>
        public static string LangText {
            get {
                return ResourceManager.GetString("LangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from OAuth 2.0.
        /// </summary>
        public static string OAuthConnectedButtonText {
            get {
                return ResourceManager.GetString("OAuthConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        public static string OAuthConnectedText {
            get {
                return ResourceManager.GetString("OAuthConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to OAuth 2.0.
        /// </summary>
        public static string OAuthDisconnectedButtonText {
            get {
                return ResourceManager.GetString("OAuthDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string WebSocketApplicationNameText {
            get {
                return ResourceManager.GetString("WebSocketApplicationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from WebSocket.
        /// </summary>
        public static string WebSocketConnectedButtonText {
            get {
                return ResourceManager.GetString("WebSocketConnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection ID.
        /// </summary>
        public static string WebSocketConnectionIdText {
            get {
                return ResourceManager.GetString("WebSocketConnectionIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Time.
        /// </summary>
        public static string WebSocketConnectionTimeText {
            get {
                return ResourceManager.GetString("WebSocketConnectionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to WebSocket.
        /// </summary>
        public static string WebSocketDisconnectedButtonText {
            get {
                return ResourceManager.GetString("WebSocketDisconnectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string WebSocketDisconnectText {
            get {
                return ResourceManager.GetString("WebSocketDisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty Connection).
        /// </summary>
        public static string WebSocketEmptyConnectionName {
            get {
                return ResourceManager.GetString("WebSocketEmptyConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Refresh WebSocket List.
        /// </summary>
        public static string WebSocketListRefreshText {
            get {
                return ResourceManager.GetString("WebSocketListRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket Connections.
        /// </summary>
        public static string WebSocketText {
            get {
                return ResourceManager.GetString("WebSocketText", resourceCulture);
            }
        }
    }
}
